import { useEffect, useMemo, useRef, useState } from 'react'
import { chapters, lessons, models, topics, validateContent } from './data'
import { storage } from './storage'
import type { AppSettings, Lesson, Mastery, ProgressRecord, StudySession } from './types'
import ModelLab from './components/ModelLab'
import { AssortmentSimulator, EvolutionTimeline, ExperimentLab, PunnettSquare } from './components/Interactions'

type Page = 'home'|'courses'|'topics'|'models'|'profile'
const masteryName:Record<Mastery,string>={unstarted:'未学习',reviewing:'复习中',mastered:'已掌握'}
const empty=(id:string):ProgressRecord=>({lessonId:id,mastery:'unstarted',updatedAt:'',modelExplored:false,visits:0,seconds:0})

function Logo(){return <div className="logo"><span className="logo-mark"><i/><i/><i/></span><span><strong>微观有光</strong><small>浙科生物 · 学考复习</small></span></div>}
function ProgressRing({value,size=74}:{value:number;size?:number}){return <div className="progress-ring" style={{'--p':`${value*3.6}deg`,'--size':`${size}px`} as React.CSSProperties}><span>{value}%</span></div>}

function Countdown({date}:{date:string}){
  const [now,setNow]=useState(()=>Date.now())
  useEffect(()=>{setNow(Date.now());const t=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(t)},[date])
  const target=new Date(date).getTime(); const ms=Number.isFinite(target)?Math.max(0,target-now):0
  const days=Math.floor(ms/86400000); const hours=Math.floor(ms%86400000/3600000); const mins=Math.floor(ms%3600000/60000); const secs=Math.floor(ms%60000/1000)
  return <div className="countdown" role="timer"><div><strong>{days}</strong><span>天</span></div><em>:</em><div><strong>{String(hours).padStart(2,'0')}</strong><span>时</span></div><em>:</em><div><strong>{String(mins).padStart(2,'0')}</strong><span>分</span></div><em>:</em><div><strong>{String(secs).padStart(2,'0')}</strong><span>秒</span></div></div>
}

function LessonCard({lesson,record,onOpen}:{lesson:Lesson;record:ProgressRecord;onOpen:()=>void}){
  return <button className="lesson-card" onClick={onOpen}><div className="lesson-card-top"><span className={`priority ${lesson.priority}`}>{lesson.priority}</span><span>{lesson.pages} 页</span></div><strong>{lesson.sectionNo.toString().padStart(2,'0')}</strong><h3>{lesson.title}</h3><p>{lesson.content.concepts.slice(0,2).join(' · ')}</p><div className="lesson-card-foot"><span className={`mastery-dot ${record.mastery}`}/>{masteryName[record.mastery]}<span>{lesson.minutes} min</span>{lesson.modelId&&<b>3D</b>}</div></button>
}

function Home({progress,settings,onPage,onOpen}:{progress:Map<string,ProgressRecord>;settings:AppSettings;onPage:(p:Page)=>void;onOpen:(l:Lesson)=>void}){
  const mastered=lessons.filter(l=>progress.get(l.id)?.mastery==='mastered').length
  const reviewing=lessons.filter(l=>progress.get(l.id)?.mastery==='reviewing')
  const recommend=reviewing[0]||lessons.find(l=>progress.get(l.id)?.mastery!=='mastered')||lessons[0]
  const recent=[...lessons].filter(l=>progress.get(l.id)?.updatedAt).sort((a,b)=>(progress.get(b.id)?.updatedAt||'').localeCompare(progress.get(a.id)?.updatedAt||'')).slice(0,3)
  return <>
    <section className="hero"><div className="hero-copy"><span className="eyebrow light">浙江高中生物学考 · 离线复习站</span><h1>把微观世界，<br/><i>看懂一点。</i></h1><p>沿着教材走，也可以顺着问题走。今天，从一个真正薄弱的地方开始。</p><div className="hero-actions"><button className="primary pale" onClick={()=>onOpen(recommend)}>继续复习 <span>→</span></button><button className="text-button" onClick={()=>onPage('topics')}>浏览专题</button></div></div><div className="hero-side"><span className="eyebrow light">距离生物学考</span><Countdown date={settings.examDate}/><p>{new Date(settings.examDate).toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'short'})}</p><div className="cell-art"><span/><span/><span/><i/><b/></div></div></section>
    <section className="dashboard-strip"><div><span>总体进度</span><strong>{mastered}<small> / 33 课</small></strong></div><ProgressRing value={Math.round(mastered/33*100)}/><div><span>正在复习</span><strong>{reviewing.length}<small> 课</small></strong></div><div><span>已探索模型</span><strong>{lessons.filter(l=>progress.get(l.id)?.modelExplored).length}<small> / 13</small></strong></div><div className="dashboard-note"><span>今日建议</span><p>{recommend.chapter} · {recommend.title}</p></div></section>
    <section className="page-section"><div className="section-heading"><div><span className="eyebrow">按教材前进</span><h2>九章，三十三次小胜利</h2></div><button className="text-button dark" onClick={()=>onPage('courses')}>查看全部课程 →</button></div><div className="chapter-shelf">{chapters.slice(0,5).map((c,i)=>{const ls=lessons.filter(l=>l.book===c.book&&l.chapterNo===c.no);const done=ls.filter(l=>progress.get(l.id)?.mastery==='mastered').length;return <button key={c.id} onClick={()=>onOpen(ls.find(l=>progress.get(l.id)?.mastery!=='mastered')||ls[0])}><span>0{i+1}</span><i style={{height:`${Math.max(8,done/ls.length*100)}%`}}/><strong>{c.name}</strong></button>})}</div></section>
    <section className="page-section soft"><div className="section-heading"><div><span className="eyebrow">跨章节理解</span><h2>换一条路，再看一遍</h2></div></div><div className="topic-grid home-topics">{topics.slice(0,4).map(t=><button key={t.id} style={{'--topic':t.color} as React.CSSProperties} onClick={()=>onPage('topics')}><span>{t.icon}</span><div><h3>{t.name}</h3><p>{t.description}</p></div><b>→</b></button>)}</div></section>
    <section className="page-section"><div className="two-col"><div><div className="section-heading compact"><div><span className="eyebrow">继续学习</span><h2>最近留下的脚印</h2></div></div>{recent.length?<div className="recent-list">{recent.map(l=><button key={l.id} onClick={()=>onOpen(l)}><span className={`mastery-dot ${progress.get(l.id)?.mastery}`}/><div><strong>{l.title}</strong><small>{l.book} · {l.chapter}</small></div><b>继续 →</b></button>)}</div>:<div className="empty-state">第一条学习记录，正等你写下。</div>}</div><div className="quote-card"><span>“</span><blockquote>结构不是为了背诵而存在，<br/>它是功能留下的形状。</blockquote><p>复习提示 · 遇到结构题，先问它解决了什么问题。</p></div></div></section>
  </>
}

function Courses({progress,onOpen}:{progress:Map<string,ProgressRecord>;onOpen:(l:Lesson)=>void}){
  const [book,setBook]=useState<'全部'|'必修1'|'必修2'>('全部'); const [query,setQuery]=useState(''); const [status,setStatus]=useState<'全部'|Mastery>('全部')
  const filtered=lessons.filter(l=>(book==='全部'||l.book===book)&&(status==='全部'||(progress.get(l.id)?.mastery||'unstarted')===status)&&(l.title.includes(query)||l.chapter.includes(query)||l.content.concepts.join('').includes(query)))
  return <main className="content-page"><header className="page-head"><span className="eyebrow">COURSE MAP</span><h1>按课复习</h1><p>依照教材章节前进，每一课都保留完整的知识脉络与教材页码。</p></header><div className="filter-bar"><div>{(['全部','必修1','必修2'] as const).map(x=><button className={book===x?'active':''} onClick={()=>setBook(x)} key={x}>{x}</button>)}</div><input aria-label="搜索课程" placeholder="搜索概念或课程…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="掌握状态" value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="全部">全部状态</option><option value="unstarted">未学习</option><option value="reviewing">复习中</option><option value="mastered">已掌握</option></select></div>
    {chapters.filter(c=>book==='全部'||c.book===book).map(c=>{const ls=filtered.filter(l=>l.book===c.book&&l.chapterNo===c.no);if(!ls.length)return null;const done=lessons.filter(l=>l.book===c.book&&l.chapterNo===c.no&&progress.get(l.id)?.mastery==='mastered').length;return <section className="course-chapter" key={c.id}><div className="chapter-heading"><div><span>{c.book} · 第{['一','二','三','四','五'][c.no-1]}章</span><h2>{c.name}</h2></div><div><ProgressRing size={58} value={Math.round(done/lessons.filter(l=>l.book===c.book&&l.chapterNo===c.no).length*100)}/></div></div><div className="lesson-grid">{ls.map(l=><LessonCard key={l.id} lesson={l} record={progress.get(l.id)||empty(l.id)} onOpen={()=>onOpen(l)}/>)}</div></section>})}
    {!filtered.length&&<div className="empty-state large">没有找到相符的课程，换个关键词试试。</div>}</main>
}

function Topics({progress,onOpen}:{progress:Map<string,ProgressRecord>;onOpen:(l:Lesson)=>void}){
  const [active,setActive]=useState(topics[0].id); const topic=topics.find(t=>t.id===active)!; const ls=lessons.filter(l=>l.topics.includes(active)); const done=ls.filter(l=>progress.get(l.id)?.mastery==='mastered').length
  return <main className="content-page"><header className="page-head"><span className="eyebrow">CONNECTED KNOWLEDGE</span><h1>专题复习</h1><p>打破章节边界，沿同一个生物学问题串起两册教材。</p></header><div className="topic-layout"><aside className="topic-nav">{topics.map(t=><button className={t.id===active?'active':''} style={{'--topic':t.color} as React.CSSProperties} key={t.id} onClick={()=>setActive(t.id)}><span>{t.icon}</span><div><strong>{t.name}</strong><small>{lessons.filter(l=>l.topics.includes(t.id)).length} 课</small></div></button>)}</aside><div className="topic-detail" style={{'--topic':topic.color} as React.CSSProperties}><div className="topic-banner"><span>{topic.icon}</span><div><small>专题 {topics.findIndex(t=>t.id===active)+1}</small><h2>{topic.name}</h2><p>{topic.description}</p></div><ProgressRing value={Math.round(done/ls.length*100)}/></div><div className="concept-map">{ls.slice(0,6).map((l,i)=><button onClick={()=>onOpen(l)} key={l.id} style={{'--i':i} as React.CSSProperties}><i/>{l.title.replace(/是|的/g,'').slice(0,10)}<small>{l.book}</small></button>)}<span className="map-core">{topic.icon}<small>核心专题</small></span></div><div className="lesson-grid compact-grid">{ls.map(l=><LessonCard key={l.id} lesson={l} record={progress.get(l.id)||empty(l.id)} onOpen={()=>onOpen(l)}/>)}</div>{active==='genetics'&&<div className="interactive-grid"><PunnettSquare/><AssortmentSimulator/></div>}{active==='experiment'&&<div className="interactive-grid"><ExperimentLab/></div>}{active==='evolution'&&<div className="interactive-grid"><EvolutionTimeline/></div>}</div></div></main>
}

function ModelsPage({progress,onOpen,onExplore}:{progress:Map<string,ProgressRecord>;onOpen:(l:Lesson)=>void;onExplore:(id:string)=>void}){
  const [active,setActive]=useState(models[0]); return <main className="content-page models-page"><header className="page-head"><span className="eyebrow">INTERACTIVE ATLAS</span><h1>微观模型馆</h1><p>十三个可拆解、可播放的教学模型。拖动旋转，滚轮缩放，点击结构查看名称。</p></header><div className="model-gallery"><aside>{models.map((m,i)=><button className={active.id===m.id?'active':''} onClick={()=>setActive(m)} key={m.id}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{m.name}</strong><small>{progress.get(m.lessonId)?.modelExplored?'已探索':'待探索'}</small></div></button>)}</aside><div><ModelLab model={active} onExplored={()=>onExplore(active.lessonId)}/><button className="text-button dark related" onClick={()=>onOpen(lessons.find(l=>l.id===active.lessonId)!)}>进入关联课程：{lessons.find(l=>l.id===active.lessonId)?.title} →</button></div></div></main>
}

function Profile({progress,sessions,settings,onSettings,onReload,onOpen}:{progress:Map<string,ProgressRecord>;sessions:StudySession[];settings:AppSettings;onSettings:(s:AppSettings)=>void;onReload:()=>void;onOpen:(l:Lesson)=>void}){
  const mastered=lessons.filter(l=>progress.get(l.id)?.mastery==='mastered').length; const totalSeconds=Array.from(progress.values()).reduce((s,x)=>s+x.seconds,0); const explored=lessons.filter(l=>progress.get(l.id)?.modelExplored).length
  const dates=new Set(Array.from(progress.values()).filter(x=>x.updatedAt).map(x=>x.updatedAt.slice(0,10))); let streak=0; const d=new Date(); while(dates.has(d.toISOString().slice(0,10))){streak++;d.setDate(d.getDate()-1)}
  const weakest=topics.map(t=>{const ls=lessons.filter(l=>l.topics.includes(t.id));return {t,value:Math.round(ls.filter(l=>progress.get(l.id)?.mastery==='mastered').length/ls.length*100)}}).sort((a,b)=>a.value-b.value)
  const exportData=async()=>{const data=await storage.export();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`生物复习备份-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
  const importData=async(file?:File)=>{if(!file)return;try{await storage.import(JSON.parse(await file.text()));onReload()}catch{alert('备份文件无法识别，请选择本程序导出的 JSON 文件。')}}
  const clear=async()=>{if(confirm('确定清空所有复习记录吗？此操作无法撤销。')){await storage.clear();onReload()}}
  return <main className="content-page"><header className="page-head profile-head"><div><span className="eyebrow">MY REVIEW</span><h1>我的进度</h1><p>数据只留在这台电脑里。今天做过的努力，都算数。</p></div><div className="date-setting"><label>学考时间<input type="datetime-local" value={settings.examDate} onChange={e=>{const s={...settings,examDate:e.target.value};onSettings(s);storage.saveSettings(s)}}/></label></div></header><div className="stat-grid"><div className="stat-main"><ProgressRing size={108} value={Math.round(mastered/33*100)}/><div><span>课程掌握</span><strong>{mastered} <small>/ 33</small></strong></div></div><div><span>复习时长</span><strong>{Math.floor(totalSeconds/3600)}<small>小时</small> {Math.floor(totalSeconds%3600/60)}<small>分</small></strong></div><div><span>连续学习</span><strong>{streak}<small>天</small></strong></div><div><span>模型探索</span><strong>{explored}<small>/ 13</small></strong></div></div><div className="profile-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">专题掌握</span><h2>知识版图</h2></div></div><div className="topic-bars">{topics.map(t=>{const x=weakest.find(w=>w.t.id===t.id)!;return <div key={t.id}><span>{t.name}</span><i><b style={{width:`${x.value}%`,background:t.color}}/></i><strong>{x.value}%</strong></div>})}</div></section><section className="panel"><div className="panel-head"><div><span className="eyebrow">优先复习</span><h2>从薄弱处开始</h2></div></div><div className="weak-list">{weakest.slice(0,3).map(({t,value})=>{const l=lessons.find(l=>l.topics.includes(t.id)&&(progress.get(l.id)?.mastery||'unstarted')!=='mastered');return <button key={t.id} disabled={!l} onClick={()=>l&&onOpen(l)}><span style={{color:t.color}}>{t.icon}</span><div><strong>{t.name}</strong><small>{l?.title||'本专题已完成'}</small></div><b>{value}% →</b></button>})}</div></section></div><section className="panel data-panel"><div><span className="eyebrow">本机数据</span><h2>备份与恢复</h2><p>导出一份 JSON 备份，换浏览器或清理数据前更安心。</p></div><div><button className="primary small" onClick={exportData}>导出备份</button><label className="ghost small file-button">导入备份<input type="file" accept="application/json" onChange={e=>importData(e.target.files?.[0])}/></label><button className="danger small" onClick={clear}>清空记录</button></div></section><p className="privacy-note">共记录 {sessions.length} 次完整学习会话 · 所有数据仅保存在当前浏览器的 IndexedDB 中</p></main>
}

function LessonDetail({lesson,record,onClose,onMastery,onExplore}:{lesson:Lesson;record:ProgressRecord;onClose:(seconds:number)=>void;onMastery:(m:Mastery)=>void;onExplore:()=>void}){
  const started=useRef(Date.now()); const model=lesson.modelId?models.find(m=>m.id===lesson.modelId):undefined
  const sections=[['学习目标',lesson.content.goals],['核心概念',lesson.content.concepts],['概念与过程',lesson.content.process],['教材实验',lesson.content.experiments],['易错辨析',lesson.content.pitfalls],['浙江学考提示',lesson.content.examTips]] as const
  return <div className="lesson-overlay"><header><button className="round-button" onClick={()=>onClose(Math.max(5,Math.round((Date.now()-started.current)/1000)))}>←</button><Logo/><div className="lesson-status"><span>掌握度</span>{(['unstarted','reviewing','mastered'] as Mastery[]).map(m=><button className={record.mastery===m?'active':''} onClick={()=>onMastery(m)} key={m}>{masteryName[m]}</button>)}</div></header><main className="lesson-detail"><div className="lesson-intro"><div><span className="eyebrow">{lesson.book} · 第{['一','二','三','四','五'][lesson.chapterNo-1]}章 · 第{['一','二','三','四','五','六'][lesson.sectionNo-1]}节</span><h1>{lesson.title}</h1><div className="lesson-meta"><span className={`priority ${lesson.priority}`}>{lesson.priority}</span><span>建议 {lesson.minutes} 分钟</span><span>教材 {lesson.pages} 页</span></div></div><div className="mini-network">{lesson.content.network.map((x,i)=><div key={x}><span>{i+1}</span><p>{x}</p>{i<lesson.content.network.length-1&&<b>↓</b>}</div>)}</div></div><nav className="detail-anchor">{sections.map(([name])=><a key={name} href={`#${name}`}>{name}</a>)}{model&&<a href="#三维模型">三维模型</a>}</nav><div className="knowledge-layout"><article>{sections.map(([name,items],index)=><section id={name} className={`knowledge-section ${name.includes('学考')?'exam-box':''}`} key={name}><div className="section-number">{String(index+1).padStart(2,'0')}</div><div><span className="eyebrow">{name==='浙江学考提示'?'EXAM FOCUS':'KNOWLEDGE BLOCK'}</span><h2>{name}</h2>{name==='概念与过程'?<ol>{items.map(x=><li key={x}>{x}</li>)}</ol>:<ul>{items.map(x=><li key={x}>{x}</li>)}</ul>}</div></section>)}<section className="network-box"><span className="eyebrow">知识网络</span><h2>把这一课串起来</h2><div>{lesson.content.network.map((x,i)=><span key={x}>{x}{i<lesson.content.network.length-1&&<b>→</b>}</span>)}</div></section>{model&&<div id="三维模型"><ModelLab model={model} onExplored={onExplore}/></div>}<div className="lesson-finish"><span>这一课，你走到哪里了？</span><div>{(['reviewing','mastered'] as Mastery[]).map(m=><button className={record.mastery===m?'primary':'ghost'} onClick={()=>onMastery(m)} key={m}>{m==='reviewing'?'标记为复习中':'我已掌握'}</button>)}</div></div></article><aside><div className="source-card"><span>教材依据</span><strong>{lesson.book}</strong><p>{lesson.chapter}<br/>{lesson.pages} 页</p><small>知识内容依据教材整理；“学考提示”为复习建议。</small></div><div className="topic-tags"><span>关联专题</span>{lesson.topics.map(id=><b key={id}>{topics.find(t=>t.id===id)?.name}</b>)}</div></aside></div></main></div>
}

export default function App(){
  const [page,setPage]=useState<Page>('home'); const [progress,setProgress]=useState<Map<string,ProgressRecord>>(new Map()); const [sessions,setSessions]=useState<StudySession[]>([]); const [settings,setSettings]=useState<AppSettings>({examDate:'2026-07-04T10:30',schemaVersion:1}); const [selected,setSelected]=useState<Lesson|null>(null); const [ready,setReady]=useState(false)
  const load=async()=>{const [p,s,c]=await Promise.all([storage.progress(),storage.sessions(),storage.settings()]);setProgress(new Map(p.map(x=>[x.lessonId,x])));setSessions(s);setSettings(c);setReady(true)}
  useEffect(()=>{const errors=validateContent();if(errors.length)console.error('内容校验失败',errors);load()},[])
  const record=(id:string)=>progress.get(id)||empty(id)
  const update=async(id:string,patch:Partial<ProgressRecord>)=>{const current=record(id);const next={...current,...patch,lessonId:id,updatedAt:new Date().toISOString()};await storage.saveProgress(next);setProgress(new Map(progress).set(id,next))}
  const open=(l:Lesson)=>{setSelected(l);update(l.id,{visits:record(l.id).visits+1,mastery:record(l.id).mastery==='unstarted'?'reviewing':record(l.id).mastery})}
  const close=async(seconds:number)=>{if(!selected)return;const id=selected.id;const current=record(id);await update(id,{seconds:current.seconds+seconds});const session={lessonId:id,startedAt:new Date().toISOString(),seconds};await storage.saveSession(session);setSessions(x=>[...x,session]);setSelected(null)}
  const explored=(id:string)=>update(id,{modelExplored:true})
  const nav=(p:Page)=>{setPage(p);scrollTo({top:0,behavior:'smooth'})}
  if(!ready)return <div className="loading"><Logo/><span>正在展开知识地图…</span></div>
  return <div className="app-shell"><header className="topbar"><Logo/><nav>{([['home','首页'],['courses','按课复习'],['topics','专题复习'],['models','模型馆'],['profile','我的']] as [Page,string][]).map(([p,n])=><button key={p} className={page===p?'active':''} onClick={()=>nav(p)}>{n}</button>)}</nav><button className="top-progress" onClick={()=>nav('profile')}><ProgressRing size={46} value={Math.round(lessons.filter(l=>record(l.id).mastery==='mastered').length/33*100)}/><span>备考进度</span></button></header>
    {page==='home'&&<Home progress={progress} settings={settings} onPage={nav} onOpen={open}/>} {page==='courses'&&<Courses progress={progress} onOpen={open}/>} {page==='topics'&&<Topics progress={progress} onOpen={open}/>} {page==='models'&&<ModelsPage progress={progress} onOpen={open} onExplore={explored}/>} {page==='profile'&&<Profile progress={progress} sessions={sessions} settings={settings} onSettings={setSettings} onReload={load} onOpen={open}/>}<footer><Logo/><p>依据浙科版《分子与细胞》《遗传与进化》整理 · 数据仅存本机</p><button onClick={()=>nav('courses')}>回到课程 ↑</button></footer>{selected&&<LessonDetail lesson={selected} record={record(selected.id)} onClose={close} onMastery={m=>update(selected.id,{mastery:m})} onExplore={()=>explored(selected.id)}/>}</div>
}
